server:
  port: 9003

spring:
  application:
    name: springboot-rocketmq

rocketmq:
  # 生产者配置
  producer:
    groupName: rocketmq-group
    namesrvAddr: 127.0.0.1:9876
    default: false
  # 消费者配置
  consumer:
    groupName: rocketmq-group
    namesrvAddr: 127.0.0.1:9876
