apiVersion: apps/v1
kind: Deployment #对象类型
metadata:
  name: redis_delayqueue #名称
  labels:
    app: redis_delayqueue #标注
    version: -version-
spec:
  replicas: 1 #运行容器的副本数，修改这里可以快速修改分布式节点数量
  selector:
    matchLabels:
      app: redis_delayqueue
  template:
    metadata:
      labels:
        app: redis_delayqueue
    spec:
      containers: #docker容器的配置
        - name: redis_delayqueue
          image: registry.cn-shenzhen.aliyuncs.com/zk-docker-repos/docker-repos:-version- # pull镜像的地址 ip:prot/dir/images:tag
          imagePullPolicy: Always #pull镜像时机，
          ports:
            - containerPort: 9191 #容器对外开放端口

---
apiVersion: v1
kind: Service
metadata:
  name: redis_delayqueue
  labels:
    app: redis_delayqueue
spec:
  type: NodePort
  ports:
    - port: 9191
      nodePort: 30091 #service对外开放端口
  selector:
    app: redis_delayqueue